version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=qrdirect
      - POSTGRES_USER=qrdirect
      - POSTGRES_PASSWORD=devenvironment
  web:
    build: .
    command: tail -F anything
    volumes:
      - .:/code
    environment:
      - DB_NAME=qrdirect
      - DB_USER=qrdirect
      - DB_PASSWORD=devenvironment
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
    data:
